# Generated by Django 4.2.3 on 2023-07-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_number', models.CharField(max_length=50)),
                ('fournisseur', models.CharField(max_length=100)),
                ('date_facture', models.DateField()),
                ('date_dept', models.DateField()),
                ('duration', models.PositiveIntegerField(default=90)),
                ('service', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
