# Generated by Django 4.2.3 on 2023-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_client_fournisseur_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
