# Generated by Django 4.2.3 on 2023-08-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_alter_fournisseur_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
