# Generated by Django 4.2.4 on 2023-08-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
